### ISSUE TITLE
Using the bootstrap function

### ISSUE THREAD

**Issue by mostly-harmless** [dgrtwo/broom#25]
Because the boostrap function produces a grouped_df I expected it to work with dplyr::summarize as below. Apparently not. Could you give an example?

> mtcars %>%
+     group_by(vs) %>%
+     summarize(mean = mean(mpg))
Source: local data frame [2 x 2]

  vs     mean
1  0 16.61667
2  1 24.55714
> 
> mtcars %>%
+     bootstrap(10) %>% 
+     summarize(mean = mean(mpg))
Error: corrupt 'grouped_df', contains %d rows, and %s rows in groups

**Comment by dgrtwo** [comment]
Unfortunately `bootstrap` hasn't worked with `summarize` in a while (it did when the function was originally written, but stopped being compatible after a dplyr update/improvement). It relies on a manipulation of the group indices that is consistent with `do` but not `summarize`.

My understanding is that bootstrapping in the future should probably be done with the [lowliner](https://github.com/hadley/lowliner) package, which has some very slick solutions for this kind of problem; I just haven't investigated it yet. The main reason `bootstrap` is in the package is to cover the cases in the [broom manuscript](http://arxiv.org/abs/1412.3565) (and I'm certainly open to pull requests that would improve it).

In the meantime you could also work around it with `do`:

    mtcars %>% bootstrap(10) %>% do(data.frame(mean = mean(.$mpg)))

**Comment by mostly-harmless** [comment]
Thanks for the workaround David. I will look into the lowliner package as well. Thanks for the tip.




Vincent


—

**Comment by benmarwick** [comment]
I also stumbled into this recently. Fortunately we now also have a `bootstrap` in @hadley's [`modelr`](https://github.com/hadley/modelr), as well as the excellent [`purrr`](https://github.com/hadley/purrr) package (formerly lowliner), and we can do something like this with the above example:

```
library(purrr)
library(modelr)

mtcars %>%
  modelr::bootstrap(10) %>%
  mutate(mean_mpg = map_dbl(strap, ~mean(data.frame(.)$mpg)))

# A tibble: 10 × 3
            strap   .id mean_mpg
           <list> <chr>    <dbl>
1  <S3: resample>    01 20.26875
2  <S3: resample>    02 19.89062
3  <S3: resample>    03 19.20000
4  <S3: resample>    04 19.79062
5  <S3: resample>    05 19.50625
6  <S3: resample>    06 19.19063
7  <S3: resample>    07 19.40625
8  <S3: resample>    08 21.53125
9  <S3: resample>    09 19.84375
10 <S3: resample>    10 20.97812
```
I was a little surprised about the need to coerce the `resample` object in the `strap` column to a data frame in order to access the `mpg` column. Is that intentional?

**Comment by dgrtwo** [comment]
Yes, I'm generally recommending people use modelr's bootstrap rather than broom's now. Once modelr is stable and on CRAN I will deprecate broom::bootstrap.

As for needing to do as.data.frame(): a resample object is more like a promise of a data frame than an actual one (though not technically a `promise`) and only creates the object when requested. It has recently occurred to me that we should really have `$` or `[[]]` evaluate as well and I plan on submitting a modelr pull request to that effect soon!

**Comment by benmarwick** [comment]
Thanks, that's great to know! I was wondering what you plan might be for `broom::bootstrap`. Thanks very much for making that PR to modelr, hopefully that'll make `modelr::bootstrap` a bit easier to use. Great to see resampling methods becoming easy to implement in the tidyverse, thanks again!
