### ISSUE TITLE
fix_data_frame tramples non-canonical colnames of input

### ISSUE THREAD

**Issue by lianos** [dgrtwo/broom#88]
We sometimes run into data sets that have column names that can be quite ... bizarre. The tamest of these might be colum names that start with a number. Currently `fix_data_frame` tramples these names, which I think can surprise end users.

```r
library(broom)
df <- data.frame(a=1:5, b=letters[1:5])
colnames(df) <- 1:2
rownames(df) <- tail(letters, 5)
fix_data_frame(df)
##   term X1 X2
## 1    v  1  a
## 2    w  2  b
## 3    x  3  c
## 4    y  4  d
## 5    z  5  e
```

Whereas I think people might reasonably expect the data.frame returned to look something like so:

```r
##   term  1  2
## 1    v  1  a
## 2    w  2  b
## 3    x  3  c
## 4    y  4  d
## 5    z  5  e
```

**Comment by dgrtwo** [comment]
The transformation of column names (using the `data.frame` function, which in turn calls `make.names`) is intentional. When column names aren't legal R variable names, that means they're difficult to use as an input to ggplot2, dplyr, or anything with a formula. (Technically they can be referred to with backticks, but this is obscure). Part of the definition of tidy data is that each column represents a variable, so it makes sense that for output to be tidy the variables need to be 

In any case, `fix_data_frame` is mostly an internal function, meant to produce outputs for `tidy`, `augment` and other operations. I'm guessing the problem arises when you're using `augment` with existing data? Generally I think the expectations that outputs of tidy/augment/glance should have legal variable names in their columns supersedes the expectation that it keeps the column names the same as the original.

**Comment by lianos** [comment]
Thanks for the response: would you consider firing of a `warning` when fix_data_frame changes the `colnames()` of the input, at least?

I stumbled on this because I recently started banging the tires on the [biobroom](https://github.com/StoreyLab/biobroom) package.

It calls `broom::fix_data_frame` internally, and some merging of primary (expression) data and extra metadata of samples stored elsewhere (eg. `pData` or `colData` of an `ExpressionSet` or `DESeqDataSet`). Unfortunately I was working with an object (not of my making :-) that had `colnames` that start with integers, and `tidy`-ing of this dataset was failing for this reason.

I could always ask the authors of biobroom to guard against this situation upstream, but I hope you'd consider at least firing off a warning when this happens so the end user can more quickly figure out why their code might be failing.
